# Upload a Dataset to a Pinecone Vector DB

In [36]:
from pinecone import Pinecone, ServerlessSpec, AwsRegion
from pinecone_datasets import load_dataset, list_datasets
import os

### Show available datasets

In [2]:
for ds in list_datasets():
    print(ds)

ANN_DEEP1B_d96_angular
ANN_Fashion-MNIST_d784_euclidean
ANN_GIST_d960_euclidean
ANN_GloVe_d100_angular
ANN_GloVe_d200_angular
ANN_GloVe_d25_angular
ANN_GloVe_d50_angular
ANN_LastFM_d64_angular
ANN_MNIST_d784_euclidean
ANN_NYTimes_d256_angular
ANN_SIFT1M_d128_euclidean
amazon_toys_quora_all-MiniLM-L6-bm25
cohere-768
it-threat-data-test
it-threat-data-train
langchain-python-docs-text-embedding-ada-002
mnist
movielens-user-ratings
msmarco-v1-bm25-allMiniLML6V2
nq-768-tasb
quora_all-MiniLM-L6-bm25-100K
quora_all-MiniLM-L6-bm25
quora_all-MiniLM-L6-v2_Splade-100K
quora_all-MiniLM-L6-v2_Splade
squad-text-embedding-ada-002
wikipedia-simple-text-embedding-ada-002-100K
wikipedia-simple-text-embedding-ada-002-50K
wikipedia-simple-text-embedding-ada-002
yfcc-100K-filter-euclidean
yfcc-10M-filter-euclidean
yfcc-10M-filter-euclidean
youtube-transcripts-text-embedding-ada-002

### Load and Preprocess the Data

In [77]:
ds = load_dataset("amazon_toys_quora_all-MiniLM-L6-bm25")

ds.head()

Loading documents parquet files: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it]

,id,values,sparse_values,metadata,blob
0,eac7efa5dbd3d667f26eb3d3ab504464,"[0.0077547780238091946, -0.02774387039244175, ...","{'indices': [2182291806, 4287202515, 148124445...",{'amazon_category_and_sub_category': 'Hobbies ...,{'text': 'Hornby 2014 Catalogue (Hornby): Pr...
1,b17540ef7e86e461d37f3ae58b7b72ac,"[0.002257382730022073, -0.03035414218902588, 0...","{'indices': [2118423442, 2177509083, 224097760...",{'amazon_category_and_sub_category': 'Hobbies ...,{'text': 'FunkyBuys® Large Christmas Holiday E...
2,348f344247b0c1a935b1223072ef9d8a,"[-0.003095218911767006, 0.016020774841308594, ...","{'indices': [2349888478, 3814962844, 310417642...",{'amazon_category_and_sub_category': 'Hobbies ...,{'text': 'CLASSIC TOY TRAIN SET TRACK CARRIAGE...
3,e12b92dbb8eaee78b22965d2a9bbbd9f,"[-0.024034591391682625, -0.048526741564273834,...","{'indices': [2182291806, 719182917, 1942275469...",{'amazon_category_and_sub_category': 'Hobbies ...,{'text': 'HORNBY Coach R4410A BR Hawksworth Co...
4,e33a9adeed5f36840ccc227db4682a36,"[-0.07078640908002853, 0.009733847342431545, 0...","{'indices': [2182291806, 2415375917, 369727517...",{'amazon_category_and_sub_category': 'Hobbies ...,{'text': 'Hornby 00 Gauge 0-4-0 Gildenlow Salt...

In [78]:
ds_no_blob = ds.documents.drop('blob', axis=1)
ds_no_blob = ds_no_blob.drop('metadata', axis=1)
ds_no_blob['metadata'] = ds.documents['blob']
ds_no_blob

,id,values,sparse_values,metadata
0,eac7efa5dbd3d667f26eb3d3ab504464,"[0.0077547780238091946, -0.02774387039244175, ...","{'indices': [2182291806, 4287202515, 148124445...",{'text': 'Hornby 2014 Catalogue (Hornby): Pr...
1,b17540ef7e86e461d37f3ae58b7b72ac,"[0.002257382730022073, -0.03035414218902588, 0...","{'indices': [2118423442, 2177509083, 224097760...",{'text': 'FunkyBuys® Large Christmas Holiday E...
2,348f344247b0c1a935b1223072ef9d8a,"[-0.003095218911767006, 0.016020774841308594, ...","{'indices': [2349888478, 3814962844, 310417642...",{'text': 'CLASSIC TOY TRAIN SET TRACK CARRIAGE...
3,e12b92dbb8eaee78b22965d2a9bbbd9f,"[-0.024034591391682625, -0.048526741564273834,...","{'indices': [2182291806, 719182917, 1942275469...",{'text': 'HORNBY Coach R4410A BR Hawksworth Co...
4,e33a9adeed5f36840ccc227db4682a36,"[-0.07078640908002853, 0.009733847342431545, 0...","{'indices': [2182291806, 2415375917, 369727517...",{'text': 'Hornby 00 Gauge 0-4-0 Gildenlow Salt...
...,...,...,...,...
9995,44d6967f083825a5de36ad4865a65bcd,"[-0.028194401413202286, 0.020815584808588028, ...","{'indices': [537607261, 3331209479, 595801246,...",{'text': 'Batman 1966 TV Series Action Figures...
9996,08f0747b6fc6687215ffb994c3a6fb32,"[0.0005118539556860924, 0.052324745804071426, ...","{'indices': [2844778355, 1822615852, 429458463...","{'text': 'Star Wars Costume, Kids Stormtrooper..."
9997,bf6cc073f8f24e6e338190fa16f6ee9d,"[-0.0863356739282608, 0.08705731481313705, 0.0...","{'indices': [3576897476, 3982843675, 359430131...",{'text': 'Defiance Lawkeeper Metal Badge Prop ...
9998,cd783d0b8b44e631b9788b203eaaefae,"[-0.0582226887345314, -0.049953095614910126, -...","{'indices': [1790916742, 653372694, 3654969415...",{'text': 'Justice League of America Series 3 G...
9999,94d18e86e504bee1e392df7e5738b18a,"[-0.06449954211711884, 0.060524459928274155, -...","{'indices': [2844778355, 1822615852, 135046271...",{'text': 'Star Wars 1/72 Y-Wing Starfighter (B...

In [84]:
for i in range(len(ds_no_blob)):
    indices = ds_no_blob['sparse_values'][i]['indices']
    values = ds_no_blob['sparse_values'][i]['values']
    text = ds_no_blob['metadata'][i]['text']
    ds_no_blob['sparse_values'][i]['indices'] = indices[:2048]
    ds_no_blob['sparse_values'][i]['values'] = values[:2048]
    ds_no_blob['metadata'][i]['text'] = text[:40000]

In [85]:
maxlen1 = 0
maxlen2 = 0
maxlen3 = 0
for i in range(len(ds_no_blob['sparse_values'])):
    if len(ds_no_blob['sparse_values'][i]['indices']) > maxlen1:
        maxlen1 = len(ds_no_blob['sparse_values'][i]['indices'])
    
    if len(ds_no_blob['sparse_values'][i]['values']) > maxlen2:
        maxlen2 = len(ds_no_blob['sparse_values'][i]['values'])

    if len(ds_no_blob['metadata'][i]['text']) > maxlen3:
        maxlen3 = len(ds_no_blob['metadata'][i]['text'])

print(maxlen1, maxlen2, maxlen3)

2048 2048 40000

In [86]:
ds_no_blob

,id,values,sparse_values,metadata
0,eac7efa5dbd3d667f26eb3d3ab504464,"[0.0077547780238091946, -0.02774387039244175, ...","{'indices': [2182291806, 4287202515, 148124445...",{'text': 'Hornby 2014 Catalogue (Hornby): Pr...
1,b17540ef7e86e461d37f3ae58b7b72ac,"[0.002257382730022073, -0.03035414218902588, 0...","{'indices': [2118423442, 2177509083, 224097760...",{'text': 'FunkyBuys® Large Christmas Holiday E...
2,348f344247b0c1a935b1223072ef9d8a,"[-0.003095218911767006, 0.016020774841308594, ...","{'indices': [2349888478, 3814962844, 310417642...",{'text': 'CLASSIC TOY TRAIN SET TRACK CARRIAGE...
3,e12b92dbb8eaee78b22965d2a9bbbd9f,"[-0.024034591391682625, -0.048526741564273834,...","{'indices': [2182291806, 719182917, 1942275469...",{'text': 'HORNBY Coach R4410A BR Hawksworth Co...
4,e33a9adeed5f36840ccc227db4682a36,"[-0.07078640908002853, 0.009733847342431545, 0...","{'indices': [2182291806, 2415375917, 369727517...",{'text': 'Hornby 00 Gauge 0-4-0 Gildenlow Salt...
...,...,...,...,...
9995,44d6967f083825a5de36ad4865a65bcd,"[-0.028194401413202286, 0.020815584808588028, ...","{'indices': [537607261, 3331209479, 595801246,...",{'text': 'Batman 1966 TV Series Action Figures...
9996,08f0747b6fc6687215ffb994c3a6fb32,"[0.0005118539556860924, 0.052324745804071426, ...","{'indices': [2844778355, 1822615852, 429458463...","{'text': 'Star Wars Costume, Kids Stormtrooper..."
9997,bf6cc073f8f24e6e338190fa16f6ee9d,"[-0.0863356739282608, 0.08705731481313705, 0.0...","{'indices': [3576897476, 3982843675, 359430131...",{'text': 'Defiance Lawkeeper Metal Badge Prop ...
9998,cd783d0b8b44e631b9788b203eaaefae,"[-0.0582226887345314, -0.049953095614910126, -...","{'indices': [1790916742, 653372694, 3654969415...",{'text': 'Justice League of America Series 3 G...
9999,94d18e86e504bee1e392df7e5738b18a,"[-0.06449954211711884, 0.060524459928274155, -...","{'indices': [2844778355, 1822615852, 135046271...",{'text': 'Star Wars 1/72 Y-Wing Starfighter (B...

### Upsert to Pinecone

In [92]:
pc = Pinecone(api_key=os.environ['PINECONE_API_KEY'])
index_name = "toys-index"
ns = 'namespace1'

if not pc.has_index(name=index_name):
    index_config = pc.create_index(
        name=index_name,
        dimension=ds.metadata.dense_model.dimension,
        spec=ServerlessSpec(cloud="aws", region=AwsRegion.US_EAST_1)
    )

In [ ]:
index = pc.Index(index_name)

index.upsert_from_dataframe(ds_no_blob, namespace=ns)

sending upsert requests:  20%|██        | 2000/10000 [06:38<26:33,  5.02it/s]




















sending upsert requests: 100%|██████████| 10000/10000 [00:28<00:00, 350.98it/s]

UpsertResponse(upserted_count=10000, _response_info={'raw_headers': {'date': 'Mon, 09 Mar 2026 19:17:19 GMT', 'content-type': 'application/json', 'content-length': '21', 'connection': 'keep-alive', 'x-pinecone-request-lsn': '36', 'x-pinecone-request-logical-size': '1828324', 'x-pinecone-request-latency-ms': '767', 'x-envoy-upstream-service-time': '208', 'x-pinecone-response-duration-ms': '769', 'grpc-status': '0', 'server': 'envoy'}})

### Test with a Query

In [106]:
from sentence_transformers import SentenceTransformer

sentences = ["This is an example sentence", "Each sentence is converted"]

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')
embeddings = model.encode(sentences)
print(embeddings)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13485.25it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[[ 6.76568747e-02  6.34958595e-02  4.87131178e-02  7.93049559e-02
   3.74480262e-02  2.65277666e-03  3.93748954e-02 -7.09844334e-03
   5.93614392e-02  3.15370075e-02  6.00980520e-02 -5.29051870e-02
   4.06067856e-02 -2.59308219e-02  2.98427679e-02  1.12689380e-03
   7.35149458e-02 -5.03819436e-02 -1.22386619e-01  2.37028636e-02
   2.97265276e-02  4.24768589e-02  2.56338008e-02  1.99519680e-03
  -5.69190979e-02 -2.71598604e-02 -3.29035223e-02  6.60248771e-02
   1.19007044e-01 -4.58791591e-02 -7.26214722e-02 -3.25839967e-02
   5.23413755e-02  4.50552665e-02  8.25299136e-03  3.67023535e-02
  -1.39414975e-02  6.53918982e-02 -2.64272541e-02  2.06395140e-04
  -1.36643685e-02 -3.62809785e-02 -1.95043236e-02 -2.89738607e-02
   3.94270457e-02 -8.84091035e-02  2.62426934e-03  1.36713842e-02
   4.83062975e-02 -3.11565548e-02 -1.17329188e-01 -5.11690192e-02
  -8.85287449e-02 -2.18962003e-02  1.42986486e-02  4.44167629e-02
  -1.34814689e-02  7.43392408e-02  2.66382825e-02 -1.98762361e-02
   1.79191045e-02 -1.06052598e-02 -9.04263407e-02  2.13269535e-02
   1.41204849e-01 -6.47175545e-03 -1.40388391e-03 -1.53610064e-02
  -8.73571709e-02  7.22173676e-02  2.01402865e-02  4.25587334e-02
  -3.49013954e-02  3.19632672e-04 -8.02970678e-02 -3.27472128e-02
   2.85268296e-02 -5.13658002e-02  1.09389208e-01  8.19328129e-02
  -9.84039605e-02 -9.34095234e-02 -1.51292300e-02  4.51248214e-02
   4.94171716e-02 -2.51867920e-02  1.57077443e-02 -1.29290715e-01
   5.31895971e-03  4.02343972e-03 -2.34572310e-02 -6.72983080e-02
   2.92281173e-02 -2.60845330e-02  1.30625209e-02 -3.11663467e-02
  -4.82713655e-02 -5.58859706e-02 -3.87505293e-02  1.20010786e-01
  -1.03924368e-02  4.89704795e-02  5.53537197e-02  4.49359193e-02
  -4.00967291e-03 -1.02959722e-01 -2.92968899e-02 -5.83401918e-02
   2.70472206e-02 -2.20169444e-02 -7.22241700e-02 -4.13869321e-02
  -1.93298105e-02  2.73330580e-03  2.76929204e-04 -9.67588052e-02
  -1.00574709e-01 -1.41922971e-02 -8.07891190e-02  4.53925356e-02
   2.45040674e-02  5.97613938e-02 -7.38185421e-02  1.19843679e-02
  -6.63403347e-02 -7.69044906e-02  3.85157317e-02 -5.59361962e-33
   2.80013382e-02 -5.60784526e-02 -4.86601926e-02  2.15570219e-02
   6.01980537e-02 -4.81403060e-02 -3.50246690e-02  1.93314161e-02
  -1.75151899e-02 -3.89210097e-02 -3.81063158e-03 -1.70287583e-02
   2.82099545e-02  1.28290597e-02  4.71601188e-02  6.21029958e-02
  -6.43588901e-02  1.29285648e-01 -1.31231332e-02  5.23069687e-02
  -3.73680964e-02  2.89094541e-02 -1.68980807e-02 -2.37330236e-02
  -3.33491974e-02 -5.16762696e-02  1.55356564e-02  2.08803192e-02
  -1.25370761e-02  4.59578969e-02  3.72720622e-02  2.80567016e-02
  -5.90005741e-02 -1.16988719e-02  4.92181964e-02  4.70328480e-02
   7.35487416e-02 -3.70529778e-02  3.98458727e-03  1.06411958e-02
  -1.61580014e-04 -5.27166240e-02  2.75927484e-02 -3.92921828e-02
   8.44717696e-02  4.86860722e-02 -4.85877600e-03  1.79948285e-02
  -4.28569615e-02  1.23375626e-02  6.39956864e-03  4.04822752e-02
   1.48887234e-02 -1.53941717e-02  7.62947723e-02  2.37043854e-02
   4.45237607e-02  5.08194976e-02 -2.31250771e-03 -1.88737214e-02
  -1.23335542e-02  4.66002561e-02 -5.63438199e-02  6.29926547e-02
  -3.15534845e-02  3.24912295e-02  2.34672818e-02 -6.55437559e-02
   2.01709010e-02  2.57082358e-02 -1.23868426e-02 -8.36498756e-03
  -6.64377660e-02  9.43073779e-02 -3.57092619e-02 -3.42483371e-02
  -6.66351337e-03 -8.01529642e-03 -3.09711229e-02  4.33012024e-02
  -8.21395498e-03 -1.50795043e-01  3.07692420e-02  4.00718488e-02
  -3.79294269e-02  1.93207781e-03  4.00530249e-02 -8.77074823e-02
  -3.68491746e-02  8.57952517e-03 -3.19251828e-02 -1.25257978e-02
   7.35539272e-02  1.34739757e-03  2.05918960e-02  2.71097962e-33
  -5.18576913e-02  5.78360893e-02 -9.18985382e-02  3.94421965e-02
   1.05576552e-01 -1.96912140e-02  6.18402362e-02 -7.63463974e-02
   2.40880586e-02  9.40049291e-02 -1.16535515e-01  3.71198729e-02
   5.22425063e-02 -3.95851722e-03  5.72214574e-02  5.32856490e-03
   1.24016829e-01  1.39022497e-02 -1.10249734e-02  3.56053114e-02
  -3.30754481e-02  8.16574246e-02 -1.52003774e-02  6.05584756e-02
  -6.01397380e-02  3.26102450e-02 -3.48296501e-02 -1.69882067e-02
  -9.74907950e-02 -2.71483436e-02  1.74707535e-03 -7.68982023e-02
  -4.31858376e-02 -1.89985596e-02 -2.91660931e-02  5.77488206e-02
   2.41821613e-02 -1.16901994e-02 -6.21434897e-02  2.84351651e-02
  -2.37528773e-04 -2.51783449e-02  4.39634360e-03  8.12840164e-02
   3.64184715e-02 -6.04006238e-02 -3.65517624e-02 -7.93747976e-02
  -5.08529553e-03  6.69699386e-02 -1.17784329e-01  3.23744155e-02
  -4.71252315e-02 -1.34459827e-02 -9.48445424e-02  8.24948680e-03
  -1.06748939e-02 -6.81882277e-02  1.11815205e-03  2.48019844e-02
  -6.35889471e-02  2.84492951e-02 -2.61303410e-02  8.58111456e-02
   1.14682332e-01 -5.35345562e-02 -5.63588403e-02  4.26008701e-02
   1.09453779e-02  2.09578760e-02  1.00131176e-01  3.26051638e-02
  -1.84208795e-01 -3.93208303e-02 -6.91454634e-02 -6.38105348e-02
  -6.56385720e-02 -6.41253404e-03 -4.79612388e-02 -7.68133551e-02
   2.95384545e-02 -2.29948685e-02  4.17037159e-02 -2.50047147e-02
  -4.54505580e-03 -4.17136215e-02 -1.32289119e-02 -6.38357922e-02
  -2.46472098e-03 -1.37337651e-02  1.68976430e-02 -6.30398244e-02
   8.98881108e-02  4.18170802e-02 -1.85687300e-02 -1.80442132e-08
  -1.67998355e-02 -3.21578123e-02  6.30383715e-02 -4.13092338e-02
   4.44819145e-02  2.02467386e-03  6.29592836e-02 -5.17374463e-03
  -1.00444024e-02 -3.05640865e-02  3.52672301e-02  5.58581576e-02
  -4.67125215e-02  3.45102809e-02  3.29577364e-02  4.30114195e-02
   2.94361431e-02 -3.03163975e-02 -1.71107464e-02  7.37484992e-02
  -5.47909848e-02  2.77515426e-02  6.20163605e-03  1.58800576e-02
   3.42978872e-02 -5.15751448e-03  2.35079471e-02  7.53135607e-02
   1.92843582e-02  3.36197019e-02  5.09103574e-02  1.52497098e-01
   1.64207816e-02  2.70528644e-02  3.75162922e-02  2.18553636e-02
   5.66334315e-02 -3.95747349e-02  7.12313503e-02 -5.41377291e-02
   1.03775656e-03  2.11853012e-02 -3.56308743e-02  1.09017007e-01
   2.76527950e-03  3.13997380e-02  1.38424337e-03 -3.45738605e-02
  -4.59277593e-02  2.88083609e-02  7.16906926e-03  4.84684817e-02
   2.61018276e-02 -9.44077037e-03  2.82169022e-02  3.48723605e-02
   3.69098298e-02 -8.58949404e-03 -3.53205651e-02 -2.47856975e-02
  -1.91921294e-02  3.80708314e-02  5.99654019e-02 -4.22286987e-02]
 [ 8.64385739e-02  1.02762625e-01  5.39452769e-03  2.04443396e-03
  -9.96338204e-03  2.53855009e-02  4.92875688e-02 -3.06265801e-02
   6.87255189e-02  1.01365717e-02  7.75397569e-02 -9.00807083e-02
   6.10614382e-03 -5.69898598e-02  1.41715119e-02  2.80491114e-02
  -8.68464336e-02  7.64399245e-02 -1.03491262e-01 -6.77437782e-02
   6.99947253e-02  8.44250992e-02 -7.24916859e-03  1.04770362e-02
   1.34020718e-02  6.77576587e-02 -9.42086279e-02 -3.71690206e-02
   5.22617660e-02 -3.10853440e-02 -9.63406861e-02  1.57716908e-02
   2.57866625e-02  7.85244927e-02  7.89949074e-02  1.91516727e-02
   1.64356753e-02  3.10083316e-03  3.81311327e-02  2.37090643e-02
   1.05389478e-02 -4.40644845e-02  4.41738255e-02 -2.58727726e-02
   6.15378767e-02 -4.05428037e-02 -8.64140317e-02  3.19722705e-02
  -8.90717900e-04 -2.44437028e-02 -9.19721350e-02  2.33939514e-02
  -8.30293596e-02  4.41510566e-02 -2.49692816e-02  6.23020381e-02
  -1.30347221e-03  7.51395673e-02  2.46384908e-02 -6.47244304e-02
  -1.17727816e-01  3.83391902e-02 -9.11767557e-02  6.35446385e-02
   7.62739554e-02 -8.80241171e-02  9.54559539e-03 -4.69717532e-02
  -8.41740668e-02  3.88823524e-02 -1.14393599e-01  6.28857082e-03
  -3.49361487e-02  2.39750631e-02 -3.31317075e-02 -1.57244559e-02
  -3.78955342e-02 -8.81247036e-03  7.06118867e-02  3.28066275e-02
   2.03676382e-03 -1.12278938e-01  6.79718424e-03  1.22765293e-02
   3.35303247e-02 -1.36200432e-02 -2.25489885e-02 -2.25228630e-02
  -2.03194227e-02  5.04297540e-02 -7.48652816e-02 -8.22822303e-02
   7.65962526e-02  4.93392423e-02 -3.75553407e-02  1.44634601e-02
  -5.72457649e-02 -1.79954246e-02  1.09697975e-01  1.19462810e-01
   8.09226651e-04  6.17057756e-02  3.26322727e-02 -1.30780101e-01
  -1.48636609e-01 -6.16232827e-02  4.33885939e-02  2.67129280e-02
   1.39785949e-02 -3.94002423e-02 -2.52711717e-02  3.87741532e-03
   3.58664766e-02 -6.15420341e-02  3.76660749e-02  2.67564878e-02
  -3.82659286e-02 -3.54793482e-02 -2.39227246e-02  8.67977366e-02
  -1.84062980e-02  7.71039575e-02  1.39866641e-03  7.00382814e-02
  -4.77877706e-02 -7.89819807e-02  5.10814115e-02 -2.99868370e-33
  -3.91646028e-02 -2.56209122e-03  1.65210199e-02  9.48941801e-03
  -5.66219613e-02  6.57782853e-02 -4.77002785e-02  1.11661758e-02
  -5.73558360e-02 -9.16257873e-03 -2.17521135e-02 -5.59531413e-02
  -1.11422827e-02  9.32793692e-02  1.66765023e-02 -1.36723733e-02
   4.34388220e-02  1.87245884e-03  7.29949633e-03  5.16332127e-02
   4.80608530e-02  1.35341495e-01 -1.71739198e-02 -1.29698068e-02
  -7.50109330e-02  2.61107683e-02  2.69802008e-02  7.83036347e-04
  -4.87270132e-02  1.17842741e-02 -4.59580310e-02 -4.83213812e-02
  -1.95671301e-02  1.93889141e-02  1.98807362e-02  1.67432185e-02
   9.87800956e-02 -2.74088103e-02  2.34809015e-02  3.70231620e-03
  -6.14514835e-02 -1.21232902e-03 -9.50474571e-03  9.25156288e-03
   2.38443781e-02  8.61231983e-02  2.26789918e-02  5.45113231e-04
   3.47130038e-02  6.25460269e-03 -6.92772819e-03  3.92400585e-02
   1.15674799e-02  3.26279514e-02  6.22155815e-02  2.76114531e-02
   1.86883695e-02  3.55805568e-02  4.11795788e-02  1.54781966e-02
   4.22691330e-02  3.82248387e-02  1.00313323e-02 -2.83246059e-02
   4.47052419e-02 -4.10458967e-02 -4.50550858e-03 -5.44734523e-02
   2.62321103e-02  1.79862045e-02 -1.23118803e-01 -4.66952212e-02
  -1.35913556e-02  6.46710023e-02  3.57352733e-03 -1.22234058e-02
  -1.79382153e-02 -2.55502313e-02  2.37224456e-02  4.08666208e-03
  -6.51475713e-02  4.43651788e-02  4.68596146e-02 -3.25174816e-02
   4.02270816e-03 -3.97602329e-03  1.11939581e-02 -9.95597839e-02
   3.33168395e-02  8.01060498e-02  9.42692310e-02 -6.38293996e-02
   3.23151313e-02 -5.13553359e-02 -7.49874813e-03  5.30048540e-34
  -4.13194560e-02  9.49646607e-02 -1.06401429e-01  4.96590659e-02
  -3.41913737e-02 -3.16745825e-02 -1.71556156e-02  1.70102529e-03
   5.79758137e-02 -1.21779414e-03 -1.68536268e-02 -5.16912676e-02
   5.52998669e-02 -3.42647657e-02  3.08179241e-02 -3.10481377e-02
   9.27532539e-02  3.72663550e-02 -2.37397850e-02  4.45893630e-02
   1.46153476e-02  1.16239332e-01 -5.00112623e-02  3.88715975e-02
   4.24750848e-03  2.56976094e-02  3.27243581e-02  4.29907739e-02
  -1.36144664e-02  2.56122239e-02  1.06262472e-02 -8.46864358e-02
  -9.52982008e-02  1.08399846e-01 -7.51600713e-02 -1.37773566e-02
   6.37338236e-02 -4.49667685e-03 -3.25321294e-02  6.23613857e-02
   3.48052755e-02 -3.54922302e-02 -2.00222246e-02  3.66608091e-02
  -2.48837397e-02  1.01819215e-02 -7.01233149e-02 -4.31950688e-02
   2.95332689e-02 -2.94985279e-04 -3.45386416e-02  1.46676023e-02
  -9.83970016e-02 -4.70488295e-02 -8.85494798e-03 -8.89914259e-02
   3.50995921e-02 -1.29602030e-01 -4.98866029e-02 -6.12047389e-02
  -5.97797036e-02  9.46318451e-03  4.91217971e-02 -7.75026530e-02
   8.09726715e-02 -4.79257442e-02  2.34380388e-03  7.57031217e-02
  -2.40175966e-02 -1.52546111e-02  4.86738905e-02 -3.85968909e-02
  -7.04831555e-02 -1.20348148e-02 -3.88790332e-02 -7.76017159e-02
  -1.07243424e-02  1.04187867e-02 -2.13753711e-02 -9.17386636e-02
  -1.11344801e-02 -2.96066031e-02  2.46458128e-02  4.65711299e-03
  -1.63449924e-02 -3.95219624e-02  7.73373470e-02 -2.84733064e-02
  -3.69937834e-03  8.27665329e-02 -1.10409167e-02  3.13983820e-02
   5.35094179e-02  5.75145483e-02 -3.17622162e-02 -1.52911266e-08
  -7.99661279e-02 -4.76796962e-02 -8.59788433e-02  5.69616333e-02
  -4.08866294e-02  2.23832671e-02 -4.64447076e-03 -3.80130969e-02
  -3.10670901e-02 -1.07278405e-02  1.97698455e-02  7.77003216e-03
  -6.09475467e-03 -3.86376455e-02  2.80272067e-02  6.78138584e-02
  -2.35350858e-02  3.21747959e-02  8.02539568e-03 -2.39107069e-02
  -1.21998403e-03  3.14599276e-02 -5.24923950e-02 -8.06811918e-03
   3.14770476e-03  5.11496849e-02 -4.44104634e-02  6.36013448e-02
   3.85084003e-02  3.30432616e-02 -4.18728450e-03  4.95592915e-02
  -5.69604859e-02 -6.49712654e-03 -2.49793231e-02 -1.60866957e-02
   6.62288815e-02 -2.06310488e-02  1.08045764e-01  1.68547276e-02
   1.43813360e-02 -1.32127106e-02 -1.29387394e-01  6.95216581e-02
  -5.55773042e-02 -6.75413460e-02 -5.45819243e-03 -6.13593496e-03
   3.90840955e-02 -6.28779754e-02  3.74063738e-02 -1.16571141e-02
   1.29150096e-02 -5.52495159e-02  5.16075641e-02 -4.30836994e-03
   5.80247380e-02  1.86944976e-02  2.27810610e-02  3.21665853e-02
   5.37978895e-02  7.02849403e-02  7.49312192e-02 -8.41774940e-02]]

In [119]:
from pinecone import SearchQuery
import numpy as np

# Define the query
query = "Hornby Trains"
query_vector = model.encode(query)
query_vector = np.squeeze(query_vector).tolist()

results = index.query(
    namespace=ns,
    vector=query_vector,
    top_k=20,
    include_metadata=True
)

In [122]:
for match in results.matches:
    print(f"Score : {match['score']} \nProduct: {match['metadata']['text']}")
    print()

Score : 0.711777687
Product: Hornby Pennine Express Train Set (Hornby):
 LOVELY TRADITIONAL LAYOUT
 Technical Details Manufacturer recommended age:5 years and up    Additional Information ASINB00ANYSJWO Best Sellers Rank 335,242 in Toys & Games (See top 100) #568 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available14 Dec. 2012    Feedback  Would you like to update product info or give feedback on images?

Score : 0.711401
Product: Hornby The Western Spirit OO Gauge Electric Train Set (Hornby):
 Product Description There were times when trains like the Western Spirit hauled not only freight but individual coaches They ran on small branch lines that ran from the main lines to the small rural towns and villages of the British IslesThis set includes a smart 4 wheeled locomotive whose heritage can be traced back to the end of the late 19th centuryAlso included are a selection of wagons plus a small coach which emulates thise small local trains of days gone byThe oval of track with a siding adds a degree of operational interest as wagons have to be shunted to and froThis allows them to be "dropped off" and picked up on the return journey. Box Contains 1 x contains 0-4-0locomotive1 x 4 assorted wagons1 x Trackside accessories1 x oval of track and siding1 x trakMat1 x transformer1 x controller
 Technical Details Item Weight1.8 Kg Product Dimensions80 x 30 x 8.4 cm Manufacturer recommended age:6 - 17 years Item model numberR1161 Batteries Included?No    Additional Information ASINB00BFLJP90 Customer Reviews amznJQ.onReady('popover', function() { (function($) { if($.fn.acrPopover) return; var popoverConfig = { showOnHover:true, showCloseButton: "ontouchstart" in document.documentElement, width: null, location:'bottom', locationAlign:'left', locationOffset:[-20,0], group: 'reviewsPopover', clone:false, hoverHideDelay:300 }; $.fn.acrPopover = function() { return this.each(function() { var $this = $(this); if(!$this.data('init') && typeof $this.amazonPopoverTrigger === 'function') { $this.data('init', 1); var ajaxURL = '/gp/customer-reviews/common/du/displayHistoPopAjax.html?' + '&ASIN=' + $this.attr('name') + '&link=1' + '&seeall=1' + '&ref=' + $this.attr('ref'); var myConfig = $.extend(true, { destination: ajaxURL }, popoverConfig); $this.amazonPopoverTrigger(myConfig); } }); }; window.reviewHistPopoverConfig = popoverConfig; var jqInit = window.jQueryInitHistoPopovers = function(asin) { if (typeof $('.acr-popover[name=' + asin + ']').acrPopover === 'function') { $('.acr-popover[name=' + asin + ']').acrPopover(); } }; window.doInit_average_customer_reviews = jqInit; window.onAjaxUpdate_average_customer_reviews = jqInit; window.onCacheUpdate_average_customer_reviews = jqInit; window.onCacheUpdateReselect_average_customer_reviews = jqInit; amznJQ.onCompletion('amznJQ.criticalFeature', function() { setTimeout(function() { amznJQ.declareAvailable('acrPopover'); }, 10); }); })(jQuery); }); amznJQ.onReady('acrPopover', function() { jQuery('.acr-popover').each(function() { if (typeof jQuery(this).acrPopover === 'function') { jQuery(this).acrPopover(); } }); }); 4.4 out of 5 stars See all reviews 7 reviews 4.4 out of 5 stars Best Sellers Rank 94,448 in Toys & Games (See top 100) #57 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight1.8 Kg Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available4 Oct. 2010    Feedback  Would you like to update product info or give feedback on images?

Score : 0.707495689
Product: Hornby R3064 RailRoad BR Smokey Joe 00 Gauge Steam Locomotive (Hornby):
 Product Description The BR 0-4-0ST loco in the famous 'Smokey Joe' livery.Young or old, keen modeller or just a beginner, the Hornby RailRoad range answers the needs of many and is a perfect complement to the variety of locomotives, rolling stock, track, buildings, and accessories that can be found in the current Hornby catalogue. Devoid of easily damaged detail parts the suitably livered RailRoad locomotives are fitted with efficient drive mechanisms and have pickups on all drive wheels ensuring smooth running. All the RailRoad models are fitted with the standard Hornby hook and bar type couplings and will therefore easily couple to those locomotives and rolling stock in both the standard Hornby and Thomas & Friends ranges. With this in mind it is easy to see that those models that make up the Hornby RailRoad range are a simple and cost effective way of adding to a train set providing a suitable and most appropriate stepping stone into the varied and fascinating World of model railways.The introductory range offers not only a selection of individual locomotives, rolling stock and accessories but an assortment of train and wagon packs ideally suited for either train set rolling stock enhancements or for those who wish to experiment and try their hands at developing their modelling techniques!This locomotive is suitable with analogue train layouts only and is not DCC compatible. Box Contains 1 x locomotive
 Technical Details Item Weight200 g Product Dimensions18.4 x 10.2 x 6 cm Manufacturer recommended age:3 years and up Item model numberR3064 Scale1:76 Engine Typeelectric Track Width/GaugeOO Batteries Required?Yes Batteries Included?No    Additional Information ASINB004QGQEMC Customer Reviews amznJQ.onReady('popover', function() { (function($) { if($.fn.acrPopover) return; var popoverConfig = { showOnHover:true, showCloseButton: "ontouchstart" in document.documentElement, width: null, location:'bottom', locationAlign:'left', locationOffset:[-20,0], group: 'reviewsPopover', clone:false, hoverHideDelay:300 }; $.fn.acrPopover = function() { return this.each(function() { var $this = $(this); if(!$this.data('init') && typeof $this.amazonPopoverTrigger === 'function') { $this.data('init', 1); var ajaxURL = '/gp/customer-reviews/common/du/displayHistoPopAjax.html?' + '&ASIN=' + $this.attr('name') + '&link=1' + '&seeall=1' + '&ref=' + $this.attr('ref'); var myConfig = $.extend(true, { destination: ajaxURL }, popoverConfig); $this.amazonPopoverTrigger(myConfig); } }); }; window.reviewHistPopoverConfig = popoverConfig; var jqInit = window.jQueryInitHistoPopovers = function(asin) { if (typeof $('.acr-popover[name=' + asin + ']').acrPopover === 'function') { $('.acr-popover[name=' + asin + ']').acrPopover(); } }; window.doInit_average_customer_reviews = jqInit; window.onAjaxUpdate_average_customer_reviews = jqInit; window.onCacheUpdate_average_customer_reviews = jqInit; window.onCacheUpdateReselect_average_customer_reviews = jqInit; amznJQ.onCompletion('amznJQ.criticalFeature', function() { setTimeout(function() { amznJQ.declareAvailable('acrPopover'); }, 10); }); })(jQuery); }); amznJQ.onReady('acrPopover', function() { jQuery('.acr-popover').each(function() { if (typeof jQuery(this).acrPopover === 'function') { jQuery(this).acrPopover(); } }); }); 4.6 out of 5 stars See all reviews 38 reviews 4.6 out of 5 stars Best Sellers Rank 33,134 in Toys & Games (See top 100) #14 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Locomotives Shipping Weight200 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available3 Mar. 2011    Feedback  Would you like to update product info or give feedback on images?

Score : 0.705217421
Product: Hornby R1138 GWR Passenger Freight 00 Gauge Electric Train Set (Hornby):
 Product Description Hornby R1138 GWR Passenger Freight OO Gauge Electric Train Set Versatile freight transport The versatile GWR 0-4-0 locomotive makes easy work of hauling the two open wagons and the small coach around the oval of track. The circuit includes an additional siding, providing an area where selected wagons can be deposited and collected again as the train travels the circuit. GWR Passenger Freight The train includes a 0-4-0 locomotive, two wagons and a four-wheel coach. It is operated using the R8250 train controller provided. Why choose a Hornby Analogue train set? Hornby's analogue sets represent the classic origins of Hornby's world famous model trains. In addition to track, a controller and an exquisitely detailed locomotive with carriages every Hornby set includes a Midimat (a pictorial bird's eye view of a fully sceniced layout) providing the new set owner the opportunity of seeing how by the addition of Hornby Track and Building packs a superb layout can be created. Track The track circuit sits easily on the 1600 x 1180 mm MiniMat, and by adding Hornby track and accessory packs can soon be developed into a very effective model railway layout. Extend your set in easy steps by adding track packs and TrakMat accessory packs all the way to the full layout pictured on your MidiMat. Fill out your MidiMat with additional track and building packs The track circuit in this set can be extended to fully complete the included MidiMat which, with additional Hornby Track and Building packs, can be simply and quickly built up into a truly fascinating and effective model railway layout. Additional track packs include R8221 Track Pack A, R8222 Track Pack B, R8223 Track Pack C, R8224 Track Pack D, R8225 Track Pack E, and R8226 Track Pack F. Additional building packs include R8227 Building Pack A, R8228 Building Pack B, R8229 Building Pack C, R8230 Building Pack D, and R8231 Building Pack E. Box Contains 1 x 0-4-0 locomotive1 x LWB open wagon1 x 4-wheel coach1 x 21 steel-sided wagon1 x UK transformer1 x Train controller1 x Buffer stop1 x Track LHPoint2 x Straight tracks2 x Double straight tracks1 x 2nd radius curve track8 x 3rd radius double curve tracks1 x Power track1 x Vacpipe acc bag1 x 0-4-0 locomotive instruction leaflet1 x Controller instruction leaflet1 x Trakmat (1600 x 1180 mm)
 Technical Details Item Weight2 Kg Product Dimensions59.8 x 30 x 8 cm Manufacturer recommended age:5 years and up Item model numberR1138 Main Language(s)English Assembly RequiredYes Scale1:76 Engine Typeelectric Track Width/GaugeOO Batteries Required?No Batteries Included?No Material Type(s)Plastic Remote Control Included?Yes Remote Control Typewired Radio Control Suitabilityindoor    Additional Information ASINB006ZL6976 Best Sellers Rank 56,416 in Toys & Games (See top 100) #75 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight2 Kg Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available19 Jan. 2012    Feedback  Would you like to update product info or give feedback on images?

Score : 0.698085785
Product: Hornby R2675 00 Gauge LNER Flying Scotsman Railroad Locomotive (Hornby):
 Product Description Hornby LNER Flying Scotsman R2675The most famous locomotive and train in the World features in this high range Hornby train set. The striking LNER apple green liveried Class A1 Flying Scotsman helps to recreate those wonderful days of train travel in the 1930s when the two great rivals, London North Eastern Railway and the London, Midland and Scottish Railway vied for the lucrative passenger traffic between London and Scotland. All the RailRoad models are fitted with the standard Hornby hook and bar type couplings and will therefore easily couple to those locomotives and rolling stock in both the standard Hornby and Thomas & Friends ranges. With this in mind it is easy to see that those models that make up the Hornby RailRoad range are a simple and cost effective way of adding to a train set providing a suitable and most appropriate stepping stone into the varied and fascinating World of model railways. This grand, classic locomotive comes in iconic LNER green livery. Although this locomotive is one of the more basic in the Hornby range, it is built with all the quality and design features you would expect from a classic Hornby train. Box Contains 1 x loco
 Technical Details Item Weight599 g Product Dimensions6 x 10 x 25.2 cm Manufacturer recommended age:0 months and up Item model numberR2675 Assembly RequiredNo Scale1:76 Track Width/GaugeOO Batteries Required?No Batteries Included?No    Additional Information ASINB000WDWEB8 Best Sellers Rank 297,928 in Toys & Games (See top 100) #169 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Locomotives Shipping Weight599 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available25 Sept. 2007    Feedback  Would you like to update product info or give feedback on images?

Score : 0.687172949
Product: Hornby R3246TTS LNER 2-8-2 'Cock O' The North' P2 Class with TTS Sound (Hornby):
 Suitable for the following scale(s): OO Scale
 Technical Details Manufacturer recommended age:3 years and up Manufacturer referenceR3246TTS Scale1:76 Track Width/GaugeOO    Additional Information ASINB00O25CFDO Best Sellers Rank 67,365 in Toys & Games (See top 100) #38 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Locomotives Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available30 Sept. 2014    Feedback  Would you like to update product info or give feedback on images?

Score : 0.685742378
Product: Hornby 2014 Catalogue (Hornby):
 Product Description Hornby 2014 Catalogue Box Contains 1 x one catalogue
 Technical Details Item Weight640 g Product Dimensions29.6 x 20.8 x 1 cm Manufacturer recommended age:6 years and up Item model numberR8148 Main Language(s)English manual, English Number of Game Players1 Number of Puzzle Pieces1 Assembly RequiredNo Scale1:72 Engine Typeelectric Track Width/GaugeHO Batteries Required?No Batteries Included?No Material Type(s)Paper Material Care InstructionsNo Remote Control Included?No Radio Control Suitabilityindoor Colorwhite    Additional Information ASINB00HJ208KO Best Sellers Rank 52,854 in Toys & Games (See top 100) #69 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight640 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available24 Dec. 2013    Feedback  Would you like to update product info or give feedback on images?

Score : 0.685069144
Product: Hornby 00 Gauge 152mm BR 0-6-2T Steam Locomotive Model (Hornby):
 Product Description Hornby Class N2 DCC Ready 00 Gauge BR 0-6-2T steam locomotive train model. These spritely suburban passenger locomotives designed by Sir Nigel Gresley were first introduced on to the Great Northern Railway in November 1920. The majority of the class were working out of London, Kings Cross and Moorgate however some would have been seen in the Glasgow area. Only one of the class survives. Class: N2, designer: sir nigel gresley, entered service: 1920, number built: 107, purpose: suburban passenger, wheel configuration: 0-6-2T, length: 152mm, motor: 5 pole skew wound, DCC ready: DCC ready, livery: BR (late), finish: pristine. Box Contains 1x Locomotive Model
 Technical Details Item Weight59 g Product Dimensions11.5 x 8 x 1.7 cm Manufacturer recommended age:3 years and up Item model numberR3188 Number of Game Players1 Scale1:76 Engine Typesteam Track Width/GaugeOO Batteries Included?No    Additional Information ASINB00EE8RM7I Best Sellers Rank 348,793 in Toys & Games (See top 100) #229 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Locomotives Shipping Weight59 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available12 July 2013    Feedback  Would you like to update product info or give feedback on images?

Score : 0.68410784
Product: Hornby 00 Gauge 2013 Livery Train Pack Model (Hornby):
 Product Description Hornby train pack model. Livery: BR. Class 373 Eurostar 4 car EMU in latest 2013 Eurostar livery. The Class 373 Locomotives, were designed by GEC-Alsthom, BN for Passenger use. Scale - (gauge): 00. DCC controller board installed already. Easy to use. Box Contains 1x Train Model
 Technical Details Item Weight59 g Product Dimensions11.5 x 8 x 1.7 cm Manufacturer recommended age:3 years and up Item model numberR3215 Scale1:76 Track Width/GaugeOO Batteries Included?No    Additional Information ASINB00FWT598W Best Sellers Rank 476,140 in Toys & Games (See top 100) #558 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight59 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available12 July 2013    Feedback  Would you like to update product info or give feedback on images?

Score : 0.674563468
Product: Hornby 00 Gauge 270mm BR Mk1 Corridor Composite BR Maroon Coach Model (Hornby):
 Product Description Hornby is a household name and is famous as the UK brand leader in the model railway hobby. Hornby BR Mk1 corridor composite coach BR Maroon Model. Livery: BR (maroon). Available in pristine finish, 270mm model length. Scale - (gauge): 00. Easy to use. Box Contains 1x Coach Model
 Technical Details Item Weight200 g Product Dimensions36.2 x 7.6 x 4.2 cm Manufacturer recommended age:3 years and up Item model numberR4350 Scale1:76 Track Width/GaugeOO Batteries Included?No    Additional Information ASINB00EE8UZC2 Best Sellers Rank 65,654 in Toys & Games (See top 100) #85 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight200 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available12 July 2013    Feedback  Would you like to update product info or give feedback on images?

Score : 0.673754692
Product: Hornby - Long Straight Track (Hornby):
 Product Description Hornby Use to create a straight long railway track. Features length: 670mm, Scale - (gauge): 00, handle with careSafety warning not suitable for children under 36 months because of small parts which can present a choking hazard. Box Contains 1x Track Model
 Technical Details Item Weight9 g Product Dimensions68.3 x 3 x 0.5 cm Manufacturer recommended age:4 years and up Item model numberR603 Assembly RequiredNo Scaleoo Track Width/GaugeOO Batteries Required?No Batteries Included?No    Additional Information ASINB000H5V11U Best Sellers Rank 89,916 in Toys & Games (See top 100) #120 in Toys & Games > Model Trains & Railway Sets > Accessories > Landscaping > Track Construction Shipping Weight9 g Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available10 Jan. 2007    Feedback  Would you like to update product info or give feedback on images?

Score : 0.670370162
Product: Hornby West Coast Highlander (Hornby):
 Bring the history of the railways to life with the Hornby West Coast Highlander. Relive the golden age when this freight train chugged across the British countryside, delivering goods to rural towns and villages. Great for youngsters and enthusiasts alike, this detailed set includes: 4-Wheel locomotive 4 x Cargo wagons 160 x 128cm TrakMat 155 x 113cm Oval track Accessories including telegraph poles, water pump, signals and sheds Standard train controller with mains power supply Suitable for rail lovers aged six and up.
 Technical Details Item Weight1.6 Kg Product Dimensions59.8 x 30.2 x 8 cm Manufacturer recommended age:6 years and up Item model numberR1157 Scale1:76 Track Width/GaugeOO    Additional Information ASINB008IQHBU0 Best Sellers Rank 8,589 in Toys & Games (See top 100) #10 in Toys & Games > Model Trains & Railway Sets > Rail Vehicles > Trains Shipping Weight1.6 Kg Delivery Destinations:Visit the Delivery Destinations Help page to see where this item can be delivered. Date First Available2 Aug. 2013    Feedback  Would you like to update product info or give feedback on images?
